import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    
    const NavbarItems =[
        { link: "/divine-dous/matches/newmatches", value: "New Matches" },
        { link: "/divine-dous/matches", value: "My Matches" },
        { link: "/divine-dous/matches/nearme", value: "Near Me" },
    ];

    return (

        <div className="relative bg-gray-100">
            <nav className="text-white pt-2 md:pt-3 ">
                <ul className="flex justify-center gap-2 md:gap-5 lg:gap-10 text-sm  lg:text-base font-medium">
                    {NavbarItems.map((item, index) => (
                        <li key={index} className='shadow-md px-3 md:px-6 rounded-lg lg:px-10 py-1 lg:py-2 bg-red-400 border-black text-center'>
                            <Link href={item.link} className=' '>
                                {item.value}
                            </Link>
                        </li>
                    ))}
                </ul>
            </nav>
            <div className="">
            {children}
            </div>
       
        </div>

    );
}
