import { Inter } from "next/font/google";

import Footer from "@/HomePageComponents/Footer";
import NavBar from "@/DivineComponents/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    
    return (

        <div className="relative bg-gray-100">
            <NavBar />
            <div className="">
            {children}
            </div>
       
        </div>

    );
}
