import React from 'react'

export default function Profiles() {
  return (
    <div>
        Virat Kohli (Hindi pronunciation: [ʋɪˈɾɑːʈ ˈkoːɦli] ⓘ; born 5 November 1988) is an Indian international cricketer and the former captain of the Indian national cricket team. He is a right-handed batsman and an occasional medium-fast bowler. He currently represents Royal Challengers Bengaluru in the IPL and Delhi in domestic cricket. Kohli is widely regarded as one of the greatest batsmen of all time.[3] He holds the record as the highest run-scorer in T20I and IPL, ranks third in ODI, and stands as the fourth-highest in international cricket.[4] He also holds the record for scoring the most centuries in ODI cricket and stands second in the list of most international centuries scored. Kohli was a member of the Indian team that won the 2011 Cricket World Cup, 2013 ICC Champions Trophy, and captained India to win the ICC Test mace three consecutive times in 2017, 2018, and 2019.[5]

In 2013, Kohli was ranked number one in the ICC rankings for ODI batsmen. In 2015, he achieved the summit of T20I rankings.[6] In 2018, he was ranked top Test batsman, making him the only Indian cricketer to hold the number one spot in all three formats of the game. He is the first player to score 20,000 runs in a decade. In 2020, the International Cricket Council named him the male cricketer of the decade.[7]

He has received many accolades for his performances in cricket. He won the ICC ODI Player of the Year award four times in 2012, 2017, 2018, and 2023. He also won the Sir Garfield Sobers Trophy, given to the ICC Cricketer of the Year, on two occasions, in 2017 and 2018 respectively. In 2018, he became the first player to win both ICC ODI and Test Player of the Year awards in the same year. Also, he was named the Wisden Leading Cricketer in the World for three consecutive years, from 2016 to 2018. At the national level, Kohli was honoured with the Arjuna Award in 2013, the Padma Shri in 2017, and India's highest sporting honour, the Khel Ratna award, in 2018.

In 2018, Time magazine included him on its list of the 100 most influential people in the world. Kohli has been deemed one of the most commercially viable athletes, with estimated earnings of ₹634 crore (US$79 million) in the year 2022.

Early life
Virat Kohli was born on 5 November 1988 in Delhi into a Punjabi Hindu family. His father, Prem Nath Kohli, worked as a criminal lawyer, and his mother, Saroj Kohli, served as a housewife. He has an older brother, Vikas, and an older sister, Bhawna.[8] Kohli's formative years were spent in Uttam Nagar. He commenced his early education at Vishal Bharti Public School.[9] According to his family, Kohli exhibited an early affinity for cricket as a mere three-year-old. He would pick up a cricket bat, display natural skill, and request his father to bowl to him.[10]

In 1998, the West Delhi Cricket Academy (WDCA) was created. On 30 May of that year, Prem Kohli, who'd espoused his younger son's fervour for cricket, assisted nine-year-old Kohli's aspirations and arranged for him to meet Rajkumar Sharma.[11] Upon the suggestion of their neighbours, Kohli's father considered enrolling his son in a professional cricket academy, as they believed that his cricketing abilities merited more than just playing in gully cricket.[12] Despite his abilities, he faced the setback of being unable to secure a place in the under-14 Delhi team, supposedly due to extraneous factors. Prem Kohli reportedly received offers to relocate his son to influential clubs, which would have ensured his selection, but he declined the proposals. Kohli eventually found his way into the under-15 Delhi team.[13] He received training at the academy while simultaneously participating in matches at the Sumeet Dogra Academy located at Vasundhara Enclave.[14] In pursuit of furthering his cricketing career, he transitioned to Saviour Convent School during his ninth-grade education.[12]

On 18 December 2006, Kohli experienced the loss of his father due to a cerebral attack.[12][15] During his childhood, his father played a crucial role in supporting his cricket training. Kohli has credited his father as the one who drove him to practice every day. He has expressed his feelings of missing his father's presence at times.[9][16] According to his mother, Kohli's demeanour shifted noticeably after his father's death. He took cricket with newfound seriousness, prioritizing playing time and dedicating himself fully to the sport.[12] Kohli's family resided in Meera Bagh, Paschim Vihar until the year 2015, after which they relocated to Gurgaon.[17]

Career
Main article: Career of Virat Kohli
Player profile
Comparisons to Sachin Tendulkar
Kohli's batting style and approach to the game have frequently drawn comparisons to the legendary Sachin Tendulkar, who he regarded as the epitome of excellence in the sport of cricket. Dubbed as Tendulkar's "successor",[18][19] he is widely considered to have the potential to surpass his records in the future.[20][21] His reverence for Tendulkar as a role model, who he idolized in his formative years and sought to emulate, is well-documented. Kohli has stated that he tried to mirror Tendulkar's style of batting, imitating his shots and attempting to hit sixes in a similar manner.[22] Kohli's aggressive and dynamic style has earned him accolades from cricketing greats such as Vivian Richards, who has acknowledged Kohli's similarities to his own playing style.[23] He has been lauded as the "new king of world cricket" by Dean Jones, a former Australian cricketer.[24] While Indian commentator Aakash Chopra has noted that Tendulkar possessed a broader array of shots,[25] Kohli's skills with the bat have earned him accolades from former West Indies great Brian Lara, who has ranked him among the best batsmen in the world alongside Joe Root, the England captain at the time.[26]

In a discourse with the prominent Bollywood actor Salman Khan, Tendulkar proclaimed that Kohli possesses the potential to surpass his record of 100 international centuries. Tendulkar also acknowledged Kohli's batting aptitudes and the steadfastness with which he has accumulated runs.[27] In 2013, Tendulkar retired from international cricket, marking the end of an era for Indian cricket. Kohli, who played alongside Tendulkar in the team, honoured him by presenting him with a sacred thread that had been gifted to him by his late father. Tendulkar eventually returned the thread to him, imploring that it should remain in his possession.[28]

Playing style
Kohli is considered as an enterprising batsman, possessing technical abilities and a dynamic playing demeanour.[29][30] His customarily batting position in ODl cricket is at number three, with a slightly open-chested stance,[31] and a resolute grip on the bottom handle of his bat. He has been noted for his agile footwork, expansive range of strokes, and his propensity for adeptly orchestrating innings whilst thriving in high-pressure situations.[32][33] In his batting technique, Kohli tends to favour playing grounded shots rather than attempting big hits. He is appreciated for his ability to execute wrist shots and his consistent prowess in the mid-wicket and cover region.[34][35]


Kohli playing his famous flick shot at the 2015 Cricket World Cup
Kohli has often expressed his admiration for the cover drive, which he considers to be his signature stroke. He possesses a natural aptitude for the flick shot, particularly when facing deliveries aimed towards leg stump.[10] Having a limited recourse to the sweep shot, Kohli's batting technique is characterized by an emphasis on ground shots that primarily yield runs in the regions between deep square leg and mid-on.[36] Kohli is known for his composed batting technique and versatility in his play. He scores runs between long-off and long-on with an aligned bat, while also possessing the ability to display a destructive streak. His combination of bat-speed and supple wrist movements enable him to craft innovative angles that disrupt traditional field positioning.[37] Kohli is also a proficient fielder, recognized for his quick reflexes and sure-handedness.[38]

However, Kohli has a known vulnerability to deliveries that are wide of the off-stump.[39] Bowlers often exploit this weakness by targeting him with such deliveries, especially in Test and ODl matches.[40] This vulnerability has resulted in Kohli's dismissal on numerous occasions.[41][42] Cricket experts such as VVS Laxman and former India cricketer Sanjay Manjrekar have acknowledged this weakness,[43][44] and former New Zealand cricketer Richard Hadlee has also noted that Kohli is particularly susceptible to out-swinging deliveries.[45]

Kohli has garnered widespread acclaim and recogniti
    </div>
  )
}
