const profileData = {
    "CreatedFor": "Self",
    "Gender": "male",
    "FirstName": "John",
    "LastName": "Doe",
    "MaritalStatus": "Single",
    "DateOfBirth": "1990-05-12",
    "Height": "6'0",
    "Disability": "None",
    "HealthInformation": "No Health Problems",
    "Diet": "Non-vegetarian",
    "aboutYourself": "Namaste! I'm John Doe, a cheerful soul navigating through life's journey with a smile. Professionally, I'm dedicated to crafting digital wonders as a web developer, but in matters of the heart, I'm searching for that special someone to share laughter, love, and unforgettable moments. Beyond the screen, I find joy in exploring nature's wonders, savoring delicious cuisines, and immersing myself in captivating stories through books and movies. I believe in the beauty of simplicity and cherish meaningful connections that add color to life's canvas.I'm on the lookout for a partner who shares my values of kindness, honesty, and positivity. Someone who embraces life's adventures with an open heart and a curious mind. Whether we're discussing the intricacies of coding or marveling at the beauty of a sunset, I believe in nurturing a relationship built on trust, respect, and laughter.",
    "ChurchName": "",
    "ChurchAddress": "",
    "IsBaptized": "",
    "BaptismDate": "",
    "FatherStatus": "Business",
    "MotherStatus": "Homemaker",
    "FamilyType": "nuclear",
    "FamilyTradition": "moderate",
    "AffluenceLevel": "middle class",
    "NoofSiblings": "2",
    "Religion": "Christianity",
    "motherTongue": "English",
    "EthnicOrigin": "Caucasian",
    "denominations": "Protestant",
    "NativeCity": "New York",
    "LivingCountry": "USA",
    "LivingState": "California",
    "LivingCity": "Los Angeles",
    "ResidencyStatus": "citizen",
    "Qualification": "Bachelor's",
    "Degree": "Computer Science",
    "WorkingSector": "Technology",
    "WorkingAsRole": "Software Engineer",
    "WorkingWith": "XYZ Tech Inc.",
    "Salary": "$90,000",
    "GamilAddress": "john.doe@example.com",
    "password": "password123",
    "ReEnterpassword": "password123",
    "number": "+1 (555) 123-4567",
    "lookingforMaxAge": "35",
    "lookingforMinAge": "25",
    "lookingforMaxHeight": "6'4\"",
    "lookingforMinHeight": "5'5\"",
    "lookingforMaritalStatus": "single",
    "lookingforEthnicOrigin": "Any",
    "lookingforReligion": "Christianity",
    "lookingforDenomination": "Any",
    "lookingforAnnualIncome": "$60,000 - $120,000",
    "lookingforProfileCreatedby": "self or family",
    "lookingforDiet": "Any",
    "lookingforCountryLiving": "USA",
    "lookingforStateLiving": "Any",
    "lookingforCity": "Any",
    "lookingforQualification": "Any",
    "lookingforDegree": "Any",
    "lookingforWorkingSector": "Any",
    "lookingforWorkingAsRole": "Any"
};

export default profileData;