import React from 'react'

const FakeMatcheData ={
    "CreatedFor": "Self",
    "Gender": "female",
    "FirstName": "Emily",
    "LastName": "Smith",
    "MaritalStatus": "Single",
    "DateOfBirth": "1992-09-28",
    "Height": "5'6",
    "Disability": "None",
    "HealthInformation": "Excellent Health",
    "Diet": "Vegetarian",
    "aboutYourself": "Hello there! I'm Emily Smith, a vibrant and compassionate individual journeying through life with enthusiasm and grace. By profession, I'm a dedicated educator, nurturing young minds and fostering a love for learning. Outside the classroom, I find solace in nature's embrace, indulging in long walks amidst lush greenery and soaking in the beauty of sunsets. I'm an avid reader, finding joy in the pages of classic literature and contemporary novels alike. Passionate about health and wellness, I prioritize a balanced lifestyle, savoring wholesome vegetarian meals and staying active through yoga and dance. I believe in the power of empathy, kindness, and authentic connections. I'm seeking a partner who shares my values, someone who values communication, mutual respect, and shared laughter. Together, let's embark on a journey filled with love, growth, and beautiful moments.",
    "ChurchName": "",
    "ChurchAddress": "",
    "IsBaptized": "",
    "BaptismDate": "",
    "FatherStatus": "Retired",
    "MotherStatus": "Homemaker",
    "FamilyType": "nuclear",
    "FamilyTradition": "moderate",
    "AffluenceLevel": "middle class",
    "NoofSiblings": "1",
    "Religion": "Christianity",
    "motherTongue": "English",
    "EthnicOrigin": "Caucasian",
    "denominations": "Protestant",
    "NativeCity": "Seattle",
    "LivingCountry": "USA",
    "LivingState": "Washington",
    "LivingCity": "Seattle",
    "ResidencyStatus": "citizen",
    "Qualification": "Master's",
    "Degree": "Education",
    "WorkingSector": "Education",
    "WorkingAsRole": "Teacher",
    "WorkingWith": "ABC Public School",
    "Salary": "$60,000",
    "GamilAddress": "emily.smith@example.com",
    "password": "password123",
    "ReEnterpassword": "password123",
    "number": "+1 (555) 987-6543",
    "lookingforMaxAge": "38",
    "lookingforMinAge": "28",
    "lookingforMaxHeight": "6'2\"",
    "lookingforMinHeight": "5'8\"",
    "lookingforMaritalStatus": "single",
    "lookingforEthnicOrigin": "Any",
    "lookingforReligion": "Christianity",
    "lookingforDenomination": "Any",
    "lookingforAnnualIncome": "$50,000 - $100,000",
    "lookingforProfileCreatedby": "self or family",
    "lookingforDiet": "Vegetarian or Vegan",
    "lookingforCountryLiving": "USA",
    "lookingforStateLiving": "Any",
    "lookingforCity": "Any",
    "lookingforQualification": "Any",
    "lookingforDegree": "Any",
    "lookingforWorkingSector": "Any",
    "lookingforWorkingAsRole": "Any"
};

export default FakeMatcheData;

