export const page1Fields = {
    CreatedFor: "Created For is required",
    Gender: "Gender is required",
    FirstName: "First Name is required",
    LastName: "Last Name is required",
    MaritalStatus: "Marital Status is required",
    DateOfBirth: "Date of Birth is required",
    Height: "Height is required",
    Disability: "Disability is required",
    HealthInformation: "Health Information is required",
    Diet: "Diet is required",
    aboutYourself: "About Yourself is required",
};
export const page2Fields = {
    FatherStatus: "Father Status is required",
    MotherStatus: "Mother Status is required",
    FamilyType: "Family Type is required",
    FamilyTradition: "Family Tradition is required",
    AffluenceLevel: "Affluence Level is required",
    NoofSiblings: "Number of Siblings is required",
    denominations: "Denominations is required",
    motherTongue: "Mother Tongue is required",
    EthnicOrigin: "Ethnic Origin is required",
    NativeCity: "Native City is required",
    IsBaptized: "Is Baptized is required",
    BaptismDate: "Baptism Date is required",
    ChurchName: "Church Name is required",
    ChurchAddress: "Church Address is required",
};
export const page3Fields = {
    LivingCountry: "Living Country is required",
    LivingState: "Living State is required",
    LivingCity: "Living City is required",
    ResidencyStatus: "Residency Status is required",
    Qualification: "Qualification is required",
    Degree: "Degree is required",
    WorkingSector: "Working Sector is required",
    WorkingAsRole: "Working As Role is required",
    WorkingWith: "Working With is required",
    Salary: "Salary is required",
};
export const page4Fields = {
    lookingforMaxAge: "Maximum age preference is required",
    lookingforMinAge: "Minimum age preference is required",
    lookingforMaxHeight: "Maximum height preference is required",
    lookingforMinHeight: "Minimum height preference is required",
    lookingforMaritalStatus: "Marital status preference is required",
    lookingforEthnicOrigin: "Ethnic origin preference is required",
    lookingforDenomination: "Denomination preference is required",
    lookingforAnnualIncome: "Annual income preference is required",
    lookingforProfileCreatedby: "Profile created by preference is required",
    lookingforCountryLiving: "Country living preference is required",
    lookingforStateLiving: "State Living  preference is required",
    lookingforQualification: "Qualification preference is required",
    lookingforDegree: "Degree preference is required",
    lookingforWorkingSector: "Working sector preference is required",
    lookingforWorkingAsRole: "Working as role preference is required",
};
export const page5Fields = {
    GamilAddress: "Gmail Address is required",
    passward: "Password is required",
    ReEnterpassward: "Re-enter Password is required",
    number: "Number is required",
};
